version: '3.6'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    networks: 
       - wordpress-db

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: password
    networks: 
       - wordpress-db
  seleniumhub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks: 
      - wordpress-db
  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - seleniumhub
    ports:
      - "5900:5900"
    environment:
      - HUB_HOST=seleniumhub
      - HUB_PORT=4444
    networks: 
      - wordpress-db
  guacd:
    hostname: guacd
    image: guacamole/guacd
    restart: always
    networks:
      - wordpress-db
    ports:
      - "4822:4822"

  guacamole:
    image: guacamole/guacamole
    restart: always
    ports:
      - 8080:8080
    links:
      - guacd
      - mysql
    environment:
      - "GUACD_HOSTNAME=guacd"
      - "GUACD_PORT=4822"
      - "GUACAMOLE_HOME=/home"
      - "MYSQL_HOSTNAME=mysql"
      - "MYSQL_DATABASE=guacamole_db"
      - "MYSQL_USER=guacamole_user"
      - "MYSQL_PASSWORD=password"
    networks:
      - wordpress-db
networks:
  wordpress-db:
    driver: overlay
